### ISSUE TITLE
[REFACTOR] prettier-plugin-tailwindcss 설치 및 적용

### ISSUE THREAD

**Issue by nijuy** [yourssu/autumn-ssu-dating#103]
## 이슈 설명
@intersoom classname이 길어지는 경우에 코드를 읽기가 힘들어서,
자동으로 정렬해주는 플러그인 도입을 제안하고 싶습니다~!

관련 문서
- https://tailwindcss.com/blog/automatic-class-sorting-with-prettier
- https://github.com/tailwindlabs/prettier-plugin-tailwindcss

## TO-DO
- [x] `prettier-plugin-tailwindcss` 설치
- [x] `.prettierrc` 파일 플러그인 설정 추가
- [x] `*.tsx` 파일에 일괄 적용

**Comment by intersoom** [comment]
좋은 것 같습니다! 적극 찬성이에용
