### ISSUE TITLE
[CHORE] 모니터용 화면 삭제

### ISSUE THREAD

**Issue by nijuy** [yourssu/autumn-ssu-dating#107]
## 이슈 설명
v2 기획에 따라 더이상 사용하지 않는 파일/코드를 삭제합니다

## TO-DO
**모니터용 화면**
- [x] `MonitorExplore` 폴더 삭제
- [x] `App.tsx` 내 `'/monitor` 경로 삭제
- [x] 관련 리소스 삭제
- [x] api, react-query 훅 삭제

**홈 화면 내 인증코드 관련 로직**
은 추천인 코드 등록용으로 재사용 하게 되어서 삭제 취소~!

## 기타
~~월요일에 한다고 해놓고 까먹었어요~~
