### ISSUE TITLE
[CHORE] 크리스마스 버전으로 이미지 교체

### ISSUE THREAD

**Issue by nijuy** [yourssu/autumn-ssu-dating#109]
## 이슈 설명
크리스마스 버전으로 이미지를 교체합니다.

## TO-DO
- [x] 동물 캐릭터 이미지 (총 9개)
- [x] 배경화면 교체 (총 3개 추가, 기존 이미지 2개 삭제)
- [x] url별 배경화면 이미지 적용을 위한 `Layout` 컴포넌트 수정
- [x] 로그인 여부 확인하는 로직 `Layout`에 추가

## 기타
링딩동
