### ISSUE TITLE
[REFACTOR] 프로필 등록 관련 문구 수정

### ISSUE THREAD

**Issue by nijuy** [yourssu/autumn-ssu-dating#114]
## 이슈 설명
버전2 디자인에 맞게 프로필 등록과 관련된 문구를 수정합니다

## TO-DO
- [x] 본인 매력 어필 `placeholder` 수정
- [x] 등록 완료 토스트 문구 수정
  - [x] `ToastMessage` UI 수정

> ⚠ 등록 완료 토스트 문구가 타 토스트에 비해 길어서, 토스트 UI 수정도 같이 진행될 예정입니다
