### ISSUE TITLE
[REFACTOR] 크리스마스 버전에서 일반 버전으로 전환

### ISSUE THREAD

**Issue by nijuy** [yourssu/autumn-ssu-dating#158]
## AS-IS
크리스마스 두 달 지났는데 아직도 슈개팅엔 눈 내리는 중

## TO-BE
일반 버전으로 전환

## TO-DO
- [x] 동물 캐릭터 이미지 교체
- [x] 바탕화면 이미지 교체
- [x] `Layout` 내 바탕화면 로직 수정 
- [x] `Layout` 내 Topbar 인자 (title, backNav) 로직 수정
