### ISSUE TITLE
[REFACTOR] 성능 개선

### ISSUE THREAD

**Issue by intersoom** [yourssu/autumn-ssu-dating#159]
## AS-IS
<img width="1033" alt="스크린샷 2024-02-19 오후 4 27 30" src="https://github.com/yourssu/autumn-ssu-dating/assets/78731710/217402f4-7778-415f-aa30-a2925d6d13da">

[라이트하우스 검사 결과](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fppussung-dating.soomsil.de%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext)

## TO-BE

가장 큰 문제는 이미지 로드인 것 같습니다! 
png를 대신해서 WebP 사용 / imgCDN 사용 등 이미지 로드 속도를 개선할 수 있는 방법을 모색해보면 좋을 것 같아요 !

지속적으로 pretendard 로드와 관련된 문제들이 라이트하우스에서 표시 되더라고요 ! 효율적인 웹폰트 import 방법을 모색해보면 좋을 것 같아요 !

캐싱 데이터 적극적으로 활용 ! 정적 리소스 캐싱 ([참고 자료](https://developer.chrome.com/docs/lighthouse/performance/uses-long-cache-ttl?utm_source=lighthouse&utm_medium=lr&hl=ko))

## TO-DO

- [x] pretendard 웹폰트 로딩 개선
- [ ] 쓰이지 않는 js 파일 정리 (/assets/index-f522c890.js)
- [x] 해당 부분 로딩 개선 (원인 파악부터... 왜일까요..? 🤔)
        <img width="756" alt="스크린샷 2024-02-19 오후 4 40 13" src="https://github.com/yourssu/autumn-ssu-dating/assets/78731710/f578ecdc-6c85-47cc-9b71-5c1ea962ccb9">
- [x] 이미지 로딩 개선
- [ ] 정적 리소스 캐싱 사용
<img width="723" alt="스크린샷 2024-02-19 오후 4 52 49" src="https://github.com/yourssu/autumn-ssu-dating/assets/78731710/08e2749d-dcdf-4741-9061-c67356ed4c95">

- [x] gif -> lottie

- [ ] meta 데이터 최적화 (SEO 증가) [참고 블로그](https://velog.io/@chl4842/react-helmet-react-snap-%EC%9C%BC%EB%A1%9C-%EB%A9%94%ED%83%80%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%B5%9C%EC%A0%81%ED%99%94%ED%95%98%EA%B8%B0)

- [x] preconnect 활용
<img width="719" alt="스크린샷 2024-02-19 오후 4 49 25" src="https://github.com/yourssu/autumn-ssu-dating/assets/78731710/526c9369-739a-48f3-a5fd-6f5ff940a643">

## 기타

저도 성능 최적화 경험이 없어서,, 일단 제가 찾아본 대로 작성해봤는데용 ,,
틀린 부분이나 개선해야할 부분이 있다면 적극적으로 의견 부탁드립니다! 더 찾아보고 추가할 사항이 있으면 추가할게요 :)

**Comment by nijuy** [comment]
> png를 대신해서 WebP 사용 / imgCDN 사용 등 이미지 로드 속도를 개선할 수 있는 방법을 모색해보면 좋을 것 같아요 !

png에 비해 Webp, AVIF 확장자가 압축률이 높다고 알고 있는데,
브라우저 지원 측면에서 Webp가 (아주 조금 더) 낫기도 하고
피그마 플러그인에 webp exporter가 있어서 #160 부터 png -> webp 전환해보겠습니다!

일부만 바꿔봤는데 5-6배 이상 용량 차이가 나네용 덜덜

![image](https://github.com/yourssu/autumn-ssu-dating/assets/87255462/6ddcc2f3-ec07-467e-8658-810dc0e4a3e4)
