### ISSUE TITLE
[REFACTOR] web font를 local font로 대체

### ISSUE THREAD

**Issue by nijuy** [yourssu/autumn-ssu-dating#161]
## AS-IS
web font 방식으로 pretendard 폰트를 로딩하고 있음.
lighthouse로 검사했을 때 관련 주의사항이 와르르

## TO-BE
woff2 파일을 assets에 넣어놓고 쓴다

## TO-DO
- [x] woff2 파일 추가
- [x] index.css에 font-face 추가
- [ ] index.html link 태그 삭제
