### ISSUE TITLE
[FEAT] 둘러보기 페이지 제작

### ISSUE THREAD

**Issue by intersoom** [yourssu/autumn-ssu-dating#9]
## 이슈 설명
둘러보기 페이지 제작

## TO-DO
**UI TODO**
- [x] 남녀 구분 탭바
- [x] 동물 카테고리 필터링
- [x] 배경사진 설정
- [ ] 하단 그라데이션 추가
- [x] 팝업창
   - [x] 열기 전 팝업
   - [x] 열기 후 팝업

**FX TODO**
- [x] 무한 스크롤 구현
- [x] 필터링 구현
- [ ] 예외처리
- [x] 글자 복사하기 기능

## 기타

모바일 대응 고민해서 코드 짜기 🤔
