### ISSUE TITLE
[FEAT] 모니터용 전시 화면

### ISSUE THREAD

**Issue by nijuy** [yourssu/autumn-ssu-dating#96]
## 이슈 설명
모니터 전시용 화면을 제작합니다

## TO-DO
- [x] 최근 동물 15개 가져오는 api 함수 작성
- [x] 그 api 함수를 쓰는 useQuery 훅 만들기
- [x] 하트 말풍선 svg 추가
- [x] 화면 요소 추가

## 기타
딩디디딩디이이딩
